# Site settings
title: Barbara Aboagye
header-img: img/home-bg.jpg
email: barbara.aboagye@usherbrooke.ca
description: "You miss 100% of the shots you don't take - Wayne Gretzky."
baseurl: ""
url: "http://barbaraaboagye.github.io/"

#Socials

twitter_username:   awesome_ama
github_username:    barbaraaboagye
facebook_username:  barbara.aboagye
instagram_username:  asantewaa_aboagye
linkedin_username: barbara-aboagye-233ba8133


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:  
- jekyll-sitemap
- jekyll - youtube
