# Site settings
title: A Footnote to Time.
header-img: img/home-bg.jpg
email: barbaraaboagye2@gmail.com
description: "A blog about software craft, engineering and spirit."
baseurl: ""
url: "http://barbaraaboagye.github.io/"

#Socials

twitter_username:   awesome_ama
github_username:    barbaraaboagye
facebook_username:  barbara.aboagye
instagram_username:  asantewaa_aboagye
linkedin_username: barbara-aboagye-233ba8133


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:  
- jekyll-sitemap
- jekyll - youtube
